# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.8.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.8.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Judah/face_detect_n_track

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Judah/face_detect_n_track

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.8.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.8.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Judah/face_detect_n_track/CMakeFiles /Users/Judah/face_detect_n_track/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Judah/face_detect_n_track/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named personDetector

# Build rule for target.
personDetector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 personDetector
.PHONY : personDetector

# fast build rule for target.
personDetector/fast:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/build
.PHONY : personDetector/fast

Eye.o: Eye.cpp.o

.PHONY : Eye.o

# target to build an object file
Eye.cpp.o:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Eye.cpp.o
.PHONY : Eye.cpp.o

Eye.i: Eye.cpp.i

.PHONY : Eye.i

# target to preprocess a source file
Eye.cpp.i:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Eye.cpp.i
.PHONY : Eye.cpp.i

Eye.s: Eye.cpp.s

.PHONY : Eye.s

# target to generate assembly for a file
Eye.cpp.s:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Eye.cpp.s
.PHONY : Eye.cpp.s

Face.o: Face.cpp.o

.PHONY : Face.o

# target to build an object file
Face.cpp.o:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Face.cpp.o
.PHONY : Face.cpp.o

Face.i: Face.cpp.i

.PHONY : Face.i

# target to preprocess a source file
Face.cpp.i:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Face.cpp.i
.PHONY : Face.cpp.i

Face.s: Face.cpp.s

.PHONY : Face.s

# target to generate assembly for a file
Face.cpp.s:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Face.cpp.s
.PHONY : Face.cpp.s

Mouth.o: Mouth.cpp.o

.PHONY : Mouth.o

# target to build an object file
Mouth.cpp.o:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Mouth.cpp.o
.PHONY : Mouth.cpp.o

Mouth.i: Mouth.cpp.i

.PHONY : Mouth.i

# target to preprocess a source file
Mouth.cpp.i:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Mouth.cpp.i
.PHONY : Mouth.cpp.i

Mouth.s: Mouth.cpp.s

.PHONY : Mouth.s

# target to generate assembly for a file
Mouth.cpp.s:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Mouth.cpp.s
.PHONY : Mouth.cpp.s

Nose.o: Nose.cpp.o

.PHONY : Nose.o

# target to build an object file
Nose.cpp.o:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Nose.cpp.o
.PHONY : Nose.cpp.o

Nose.i: Nose.cpp.i

.PHONY : Nose.i

# target to preprocess a source file
Nose.cpp.i:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Nose.cpp.i
.PHONY : Nose.cpp.i

Nose.s: Nose.cpp.s

.PHONY : Nose.s

# target to generate assembly for a file
Nose.cpp.s:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Nose.cpp.s
.PHONY : Nose.cpp.s

Person.o: Person.cpp.o

.PHONY : Person.o

# target to build an object file
Person.cpp.o:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Person.cpp.o
.PHONY : Person.cpp.o

Person.i: Person.cpp.i

.PHONY : Person.i

# target to preprocess a source file
Person.cpp.i:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Person.cpp.i
.PHONY : Person.cpp.i

Person.s: Person.cpp.s

.PHONY : Person.s

# target to generate assembly for a file
Person.cpp.s:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/Person.cpp.s
.PHONY : Person.cpp.s

PersonDetector.o: PersonDetector.cpp.o

.PHONY : PersonDetector.o

# target to build an object file
PersonDetector.cpp.o:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/PersonDetector.cpp.o
.PHONY : PersonDetector.cpp.o

PersonDetector.i: PersonDetector.cpp.i

.PHONY : PersonDetector.i

# target to preprocess a source file
PersonDetector.cpp.i:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/PersonDetector.cpp.i
.PHONY : PersonDetector.cpp.i

PersonDetector.s: PersonDetector.cpp.s

.PHONY : PersonDetector.s

# target to generate assembly for a file
PersonDetector.cpp.s:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/PersonDetector.cpp.s
.PHONY : PersonDetector.cpp.s

VideoFaceDetector.o: VideoFaceDetector.cpp.o

.PHONY : VideoFaceDetector.o

# target to build an object file
VideoFaceDetector.cpp.o:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/VideoFaceDetector.cpp.o
.PHONY : VideoFaceDetector.cpp.o

VideoFaceDetector.i: VideoFaceDetector.cpp.i

.PHONY : VideoFaceDetector.i

# target to preprocess a source file
VideoFaceDetector.cpp.i:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/VideoFaceDetector.cpp.i
.PHONY : VideoFaceDetector.cpp.i

VideoFaceDetector.s: VideoFaceDetector.cpp.s

.PHONY : VideoFaceDetector.s

# target to generate assembly for a file
VideoFaceDetector.cpp.s:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/VideoFaceDetector.cpp.s
.PHONY : VideoFaceDetector.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/personDetector.dir/build.make CMakeFiles/personDetector.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... personDetector"
	@echo "... Eye.o"
	@echo "... Eye.i"
	@echo "... Eye.s"
	@echo "... Face.o"
	@echo "... Face.i"
	@echo "... Face.s"
	@echo "... Mouth.o"
	@echo "... Mouth.i"
	@echo "... Mouth.s"
	@echo "... Nose.o"
	@echo "... Nose.i"
	@echo "... Nose.s"
	@echo "... Person.o"
	@echo "... Person.i"
	@echo "... Person.s"
	@echo "... PersonDetector.o"
	@echo "... PersonDetector.i"
	@echo "... PersonDetector.s"
	@echo "... VideoFaceDetector.o"
	@echo "... VideoFaceDetector.i"
	@echo "... VideoFaceDetector.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

